version: "2"
services:
  rabbit:
    container_name: tofu-rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
      - "1884:1883"
    restart: always
    build:
      context: ./rabbit
      dockerfile: Dockerfile

  gateway:
    container_name: tofu-gateway
    depends_on:
      - rabbit
    ports:
      - "8000:8000"
    links:
      - "rabbit:tofu-rabbitmq"
    environment:
      RABBIT_PASSWORD: "tofu"
      RABBIT_USER: "tofu"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    build:
      context: ./gateway
      dockerfile: Dockerfile

  carts:
    container_name: tofu-carts
    depends_on:
      - rabbit
      - carts-postgres
    ports:
      - "8001:8000"
    links:
      - "rabbit:tofu-rabbitmq"
      - "carts-postgres:tofu-carts-postgres"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "carts-postgres"
      DB_NAME: "tofu_cart"
      RABBIT_PASSWORD: "tofu"
      RABBIT_USER: "tofu"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    build:
      context: ./carts
      dockerfile: Dockerfile

  search:
    container_name: tofu-search
    depends_on:
      - rabbit
      - search-postgres
    ports:
        - "8002:8000"
    links:
        - "rabbit:tofu-rabbitmq"
        - "search-postgres:tofu-search-postgres"
    environment:
        DB_PASSWORD: "password"
        DB_USER: "postgres"
        DB_HOST: "search-postgres"
        DB_NAME: "tofu_search"
        RABBIT_PASSWORD: "tofu"
        RABBIT_USER: "tofu"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
    build:
        context: ./search
        dockerfile: Dockerfile

  market-gateway:
    container_name: tofu-market-gateway
    depends_on:
      - rabbit
    ports:
      - "8003:8000"
    links:
      - "rabbit:tofu-rabbitmq"
    environment:
      RABBIT_PASSWORD: "tofu"
      RABBIT_USER: "tofu"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    build:
      context: ./market_gateway
      dockerfile: Dockerfile

  users:
    container_name: tofu-users
    depends_on:
      - rabbit
      - users-postgres
    ports:
      - "8004:8000"
    links:
      - "rabbit:tofu-rabbitmq"
      - "users-postgres:tofu-users-postgres"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "users-postgres"
      DB_NAME: "tofu_user"
      RABBIT_PASSWORD: "tofu"
      RABBIT_USER: "tofu"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    build:
      context: ./users
      dockerfile: Dockerfile
